export interface AgenciaForm {

    Proceso:number,
    Codigo:string,
    Ruc:string,
    Nombre:string,
    Direccion:string,
    Ciudad:string,
    Pais:string,
    Primario:number,
    Mercado:string,
    Contacto:string,
    Telefono:string,
    Telefono2:string,
    Fax:string,
    Email:string,
    CodHabita:string,
    NumHabita:number,
    CodReserva:string,
    NumReserva:string,
    Descuento:number,
    Activo:number,
    Operador:string,

}
