export interface ReservaForm{

    Proceso         :number,
    CodReseva       :string,
    CodAgencia      :string,
    CodTarifa       :string,
    CodPlan         :string,
    FechaIngreso    :string,
    FechaSalida     :string,
    FechaCreacion   :string,
    FechaConfirma   :string,
    FechaPrepago    :string,
    FechaAnulado    :string,
    TotalNoches     :number,
    TotalDias       :number,
    Descripcion     :string,
    TCambio         :number,
    Folio           :string,
    Estado          :string,
    Moneda          :string,
    Totalrsv        :number,
    Observaciones   :string,
    Procesa         :number,
    Directo         :string,
    Operador        :string,

}